version: '3.8'

services:
  github-achievement-generator:
    build: .
    container_name: github-achievement-gen
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - NODE_ENV=production
    volumes:
      - ./achievements:/app/achievements
      - ./.env:/app/.env:ro
    command: ["node", "scripts/generateAll.js"]
    restart: "no"

  scheduler:
    build: .
    container_name: github-achievement-scheduler
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - NODE_ENV=production
    volumes:
      - ./achievements:/app/achievements
      - ./.env:/app/.env:ro
    command: ["node", "scripts/scheduler.js"]
    restart: unless-stopped

  web-interface:
    build: .
    container_name: github-achievement-web
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./achievements:/app/achievements
      - ./.env:/app/.env:ro
    command: ["node", "src/server.js"]
    restart: unless-stopped

networks:
  default:
    name: github-achievements